spring:
  datasource:
    url: jdbc:mysql://localhost:3636/authdb
    username: iholin
    password: 3sotnibaksov
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: poormusic

jwt:
  secret: "4261656C64756E67"
  expiration-ms: 3600000